# Generated by Django 4.0.5 on 2022-06-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=60)),
                ('difficulty', models.CharField(choices=[('novice', 'bnovice'), ('beginner', 'beginner'), ('proficient', 'proficient'), ('master', 'master')], max_length=12)),
                ('text', models.TextField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_module.code')),
            ],
        ),
    ]
