# Generated by Django 4.0.5 on 2022-06-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
